import { Component, Provide, Vue } from 'vue-property-decorator';

import UserService from '@/entities/user/user.service';
import EstadoService from './estado/estado.service';
import CiudadService from './ciudad/ciudad.service';
import CPService from './cp/cp.service';
import ColoniaService from './colonia/colonia.service';
import DireccionService from './direccion/direccion.service';
import SucursalService from './sucursal/sucursal.service';
import PersonaService from './persona/persona.service';
import PersonaMoralService from './persona-moral/persona-moral.service';
import PersonaFisicaService from './persona-fisica/persona-fisica.service';
import TipoContactoService from './tipo-contacto/tipo-contacto.service';
import ContactoService from './contacto/contacto.service';
import DireccionPersonaService from './direccion-persona/direccion-persona.service';
import EmpleadoService from './empleado/empleado.service';
import HorarioService from './horario/horario.service';
import DiaHorarioService from './dia-horario/dia-horario.service';
import LicenciaManejoService from './licencia-manejo/licencia-manejo.service';
import ExperienciaHabilidadService from './experiencia-habilidad/experiencia-habilidad.service';
import EmpleadoTipoVehiculoService from './empleado-tipo-vehiculo/empleado-tipo-vehiculo.service';
import VehiculoService from './vehiculo/vehiculo.service';
import UnidadService from './unidad/unidad.service';
import PolizaService from './poliza/poliza.service';
import AditamentoService from './aditamento/aditamento.service';
import AditamentoUnidadService from './aditamento-unidad/aditamento-unidad.service';
import ClienteService from './cliente/cliente.service';
import VehiculoClienteService from './vehiculo-cliente/vehiculo-cliente.service';
import ViajeService from './viaje/viaje.service';
import ItinerarioService from './itinerario/itinerario.service';
import UnidadViajeService from './unidad-viaje/unidad-viaje.service';
import OperadorUnidadService from './operador-unidad/operador-unidad.service';
import EstanteService from './estante/estante.service';
import NivelService from './nivel/nivel.service';
import SeccionService from './seccion/seccion.service';
import ProductoService from './producto/producto.service';
import InventarioService from './inventario/inventario.service';
import UbicacionInventarioService from './ubicacion-inventario/ubicacion-inventario.service';
import ResurtirService from './resurtir/resurtir.service';
import RenglonResurtirService from './renglon-resurtir/renglon-resurtir.service';
import PrecioVentaService from './precio-venta/precio-venta.service';
import VentaService from './venta/venta.service';
import RenglonVentaService from './renglon-venta/renglon-venta.service';
import PerdidaService from './perdida/perdida.service';
import ServicioService from './servicio/servicio.service';
import MaterialServicioService from './material-servicio/material-servicio.service';
import PrecioServicioService from './precio-servicio/precio-servicio.service';
import UnidadServicioService from './unidad-servicio/unidad-servicio.service';
import ListaServicioService from './lista-servicio/lista-servicio.service';
import CitaService from './cita/cita.service';
import StatusCitaService from './status-cita/status-cita.service';
import CotizacionService from './cotizacion/cotizacion.service';
import PagoService from './pago/pago.service';
import PedidoService from './pedido/pedido.service';
import ListaPedidoService from './lista-pedido/lista-pedido.service';
import VentaPedidoService from './venta-pedido/venta-pedido.service';
import ReporteService from './reporte/reporte.service';
// jhipster-needle-add-entity-service-to-entities-component-import - JHipster will import entities services here

@Component
export default class Entities extends Vue {
  @Provide('userService') private userService = () => new UserService();
  @Provide('estadoService') private estadoService = () => new EstadoService();
  @Provide('ciudadService') private ciudadService = () => new CiudadService();
  @Provide('cPService') private cPService = () => new CPService();
  @Provide('coloniaService') private coloniaService = () => new ColoniaService();
  @Provide('direccionService') private direccionService = () => new DireccionService();
  @Provide('sucursalService') private sucursalService = () => new SucursalService();
  @Provide('personaService') private personaService = () => new PersonaService();
  @Provide('personaMoralService') private personaMoralService = () => new PersonaMoralService();
  @Provide('personaFisicaService') private personaFisicaService = () => new PersonaFisicaService();
  @Provide('tipoContactoService') private tipoContactoService = () => new TipoContactoService();
  @Provide('contactoService') private contactoService = () => new ContactoService();
  @Provide('direccionPersonaService') private direccionPersonaService = () => new DireccionPersonaService();
  @Provide('empleadoService') private empleadoService = () => new EmpleadoService();
  @Provide('horarioService') private horarioService = () => new HorarioService();
  @Provide('diaHorarioService') private diaHorarioService = () => new DiaHorarioService();
  @Provide('licenciaManejoService') private licenciaManejoService = () => new LicenciaManejoService();
  @Provide('experienciaHabilidadService') private experienciaHabilidadService = () => new ExperienciaHabilidadService();
  @Provide('empleadoTipoVehiculoService') private empleadoTipoVehiculoService = () => new EmpleadoTipoVehiculoService();
  @Provide('vehiculoService') private vehiculoService = () => new VehiculoService();
  @Provide('unidadService') private unidadService = () => new UnidadService();
  @Provide('polizaService') private polizaService = () => new PolizaService();
  @Provide('aditamentoService') private aditamentoService = () => new AditamentoService();
  @Provide('aditamentoUnidadService') private aditamentoUnidadService = () => new AditamentoUnidadService();
  @Provide('clienteService') private clienteService = () => new ClienteService();
  @Provide('vehiculoClienteService') private vehiculoClienteService = () => new VehiculoClienteService();
  @Provide('viajeService') private viajeService = () => new ViajeService();
  @Provide('itinerarioService') private itinerarioService = () => new ItinerarioService();
  @Provide('unidadViajeService') private unidadViajeService = () => new UnidadViajeService();
  @Provide('operadorUnidadService') private operadorUnidadService = () => new OperadorUnidadService();
  @Provide('estanteService') private estanteService = () => new EstanteService();
  @Provide('nivelService') private nivelService = () => new NivelService();
  @Provide('seccionService') private seccionService = () => new SeccionService();
  @Provide('productoService') private productoService = () => new ProductoService();
  @Provide('inventarioService') private inventarioService = () => new InventarioService();
  @Provide('ubicacionInventarioService') private ubicacionInventarioService = () => new UbicacionInventarioService();
  @Provide('resurtirService') private resurtirService = () => new ResurtirService();
  @Provide('renglonResurtirService') private renglonResurtirService = () => new RenglonResurtirService();
  @Provide('precioVentaService') private precioVentaService = () => new PrecioVentaService();
  @Provide('ventaService') private ventaService = () => new VentaService();
  @Provide('renglonVentaService') private renglonVentaService = () => new RenglonVentaService();
  @Provide('perdidaService') private perdidaService = () => new PerdidaService();
  @Provide('servicioService') private servicioService = () => new ServicioService();
  @Provide('materialServicioService') private materialServicioService = () => new MaterialServicioService();
  @Provide('precioServicioService') private precioServicioService = () => new PrecioServicioService();
  @Provide('unidadServicioService') private unidadServicioService = () => new UnidadServicioService();
  @Provide('listaServicioService') private listaServicioService = () => new ListaServicioService();
  @Provide('citaService') private citaService = () => new CitaService();
  @Provide('statusCitaService') private statusCitaService = () => new StatusCitaService();
  @Provide('cotizacionService') private cotizacionService = () => new CotizacionService();
  @Provide('pagoService') private pagoService = () => new PagoService();
  @Provide('pedidoService') private pedidoService = () => new PedidoService();
  @Provide('listaPedidoService') private listaPedidoService = () => new ListaPedidoService();
  @Provide('ventaPedidoService') private ventaPedidoService = () => new VentaPedidoService();
  @Provide('reporteService') private reporteService = () => new ReporteService();
  // jhipster-needle-add-entity-service-to-entities-component - JHipster will import entities services here
}
